<h1 style = "font-size:3rem;color:orange">Examen primera convocatoria 2024</h1>

Librerías

In [1]:
# Librerías
import numpy as np


## 01 - 1.25pt

- Crear un array de NumPy de dimensiones 5x5, con números enteros aleatorios en el rango [-40, 40]
- Hacer los siguientes reemplazos en orden
    - Reemplazar todos los valores multiplos de 3 por 1
    - Reemplazar todos los valores pares positivos por 0
    - Reemplazar todos los valores pares negativos por Nan
- Averiguar cuantos elementos tienen Nan por fila

In [21]:
# Array de números aleatorios de 5x5
array = np.random.randint(-40, 41, size=(5, 5))
print("Array de números aleatorios:\n{}".format(array))

# Reemplazar los valores múltiplos de 3 por 1
array = np.where(array % 3 == 0, 1, array)
print("\nReemplazo los múltiplos de 3 por 1:\n{}".format(array))

# Reemplazar todos los valores pares positivos por 0
array = np.where((array > 0) & (array % 2 == 0), 0, array)
print("\nReemplazo los valores pares positivos por 0:\n{}".format(array))

# Reemplazar todos los valores pares negativos por Nan
array = np.where((array < 0) & (array % 2 == 0), np.nan, array)
print("\nReemplazo los valores pares negativos por Nan:\n{}".format(array))

# Elementos Nan por fila en el array
row_nan = np.sum(np.isnan(array), axis=1)
print("\nElementos Nan por fila:\n{}".format(row_nan))

Array de números aleatorios:
[[-21  -8  37 -20 -40]
 [ 18  -9  -3 -13  14]
 [-23 -32 -37 -24 -34]
 [  4  30 -31  -5  -6]
 [-25  33  -1  40 -40]]

Reemplazo los múltiplos de 3 por 1:
[[  1  -8  37 -20 -40]
 [  1   1   1 -13  14]
 [-23 -32 -37   1 -34]
 [  4   1 -31  -5   1]
 [-25   1  -1  40 -40]]

Reemplazo los valores pares positivos por 0:
[[  1  -8  37 -20 -40]
 [  1   1   1 -13   0]
 [-23 -32 -37   1 -34]
 [  0   1 -31  -5   1]
 [-25   1  -1   0 -40]]

Reemplazo los valores pares negativos por Nan:
[[  1.  nan  37.  nan  nan]
 [  1.   1.   1. -13.   0.]
 [-23.  nan -37.   1.  nan]
 [  0.   1. -31.  -5.   1.]
 [-25.   1.  -1.   0.  nan]]

Elementos Nan por fila:
[3 0 2 0 1]


## 02 - 1.25pt

- Escribir un generador que genere todos los factores de un número. Un factor es un número natural que puede dividir exactamente a otro número.

In [24]:
# Your solution HERE !!!!
def factor_generator(number):
    for item in range(1, number + 1):
        if number % item == 0:
            yield item

In [27]:
number = 1000
expected_factors = [1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 125, 200, 250, 500, 1000]
gen = factor_generator(number) # This calls tour function factor_generator
output = [next(gen) for n in range(len(expected_factors))]
assert(expected_factors == output)  # This will fail if the element is not found correctly