<h1 style = "font-size:3rem;color:orange">Examen primera convocatoria 2024</h1>

Librerías

In [1]:
# Librerías
import numpy as np
import pandas as pd


C:\Users\pepel\AppData\Local\Temp\ipykernel_16080\3928729184.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## 01 - 1.25pt

- Crear un array de NumPy de dimensiones 5x5, con números enteros aleatorios en el rango [-40, 40]
- Hacer los siguientes reemplazos en orden
    - Reemplazar todos los valores multiplos de 3 por 1
    - Reemplazar todos los valores pares positivos por 0
    - Reemplazar todos los valores pares negativos por Nan
- Averiguar cuantos elementos tienen Nan por fila

In [21]:
# Array de números aleatorios de 5x5
array = np.random.randint(-40, 41, size=(5, 5))
print("Array de números aleatorios:\n{}".format(array))

# Reemplazar los valores múltiplos de 3 por 1
array = np.where(array % 3 == 0, 1, array)
print("\nReemplazo los múltiplos de 3 por 1:\n{}".format(array))

# Reemplazar todos los valores pares positivos por 0
array = np.where((array > 0) & (array % 2 == 0), 0, array)
print("\nReemplazo los valores pares positivos por 0:\n{}".format(array))

# Reemplazar todos los valores pares negativos por Nan
array = np.where((array < 0) & (array % 2 == 0), np.nan, array)
print("\nReemplazo los valores pares negativos por Nan:\n{}".format(array))

# Elementos Nan por fila en el array
row_nan = np.sum(np.isnan(array), axis=1)
print("\nElementos Nan por fila:\n{}".format(row_nan))

Array de números aleatorios:
[[-21  -8  37 -20 -40]
 [ 18  -9  -3 -13  14]
 [-23 -32 -37 -24 -34]
 [  4  30 -31  -5  -6]
 [-25  33  -1  40 -40]]

Reemplazo los múltiplos de 3 por 1:
[[  1  -8  37 -20 -40]
 [  1   1   1 -13  14]
 [-23 -32 -37   1 -34]
 [  4   1 -31  -5   1]
 [-25   1  -1  40 -40]]

Reemplazo los valores pares positivos por 0:
[[  1  -8  37 -20 -40]
 [  1   1   1 -13   0]
 [-23 -32 -37   1 -34]
 [  0   1 -31  -5   1]
 [-25   1  -1   0 -40]]

Reemplazo los valores pares negativos por Nan:
[[  1.  nan  37.  nan  nan]
 [  1.   1.   1. -13.   0.]
 [-23.  nan -37.   1.  nan]
 [  0.   1. -31.  -5.   1.]
 [-25.   1.  -1.   0.  nan]]

Elementos Nan por fila:
[3 0 2 0 1]


## 02 - 1.25pt

- Escribir un generador que genere todos los factores de un número. Un factor es un número natural que puede dividir exactamente a otro número.

In [24]:
# Your solution HERE !!!!
def factor_generator(number):
    for item in range(1, number + 1):
        if number % item == 0:
            yield item

In [27]:
number = 1000
expected_factors = [1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 125, 200, 250, 500, 1000]
gen = factor_generator(number) # This calls tour function factor_generator
output = [next(gen) for n in range(len(expected_factors))]
assert(expected_factors == output)  # This will fail if the element is not found correctly

## 03 - 1.25pt

- Escribir una función que reciba un Dataframe, en la columna "name" convierta el primer carácter de cada nombre a mayúsculas.

In [23]:
# Opción 1
def capitalize_name(dataframe):
    dataframe['name'] = dataframe['name'].apply(lambda x: x.capitalize())
    return dataframe

# Opción 2
def capitalize_name_2(dataframe):
    dataframe['name'] = dataframe['name'].str.capitalize()
    return dataframe

# Opción 3
def capitalize_name_3(dataframe):
    dataframe['name'] = dataframe['name'].str.title()
    return dataframe

In [24]:
dataframe = pd.DataFrame({
    'name': ['tamayo','tanjiro','inosuke', 'zenitsu', 'nezuko'],
    'date_of_birth ': ['13/01/2002','18/03/1999','21/11/1998','10/10/2002','05/04/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

expected_dataframe = pd.DataFrame({
    'name': ['Tamayo', 'Tanjiro', 'Inosuke', 'Zenitsu', 'Nezuko'],
    'date_of_birth ': ['13/01/2002','18/03/1999','21/11/1998','10/10/2002','05/04/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

output = capitalize_name(dataframe) # This calls your function capitalize_name
assert(expected_dataframe.equals(output)) # This will fail if result is not as expected

## 04 - 1.25pt

- 200 personas hacen una review de una película, dándole una puntuación de 0.0 a 5.0 a dicha película
- Crear una lista aleatoria con las posibles puntuaciones, es decir, 200 puntuaciones entre 0.0 y 5.0
- Discretizar dichas puntuaciones en 4 categorias [muy mala, mala, buena, excelente], los límites de cada categoría son a libre elección
- Discretizar dichas puntuaciones en 5 categorías distribuidas con rangos homogéneos (similar cantidad de valores en cada categoría)
- Mostrar las categorías creadas y cuantos elementos hay en cada una de ellas

In [59]:
# Lista aleatoria de 200 puntuaciones entre 0.0 y 5.0
review_lst = np.random.randint(0, 51, 200)
review_lst = review_lst / 10
print("Reviews:\n{}\n".format(review_lst))

# Discretización de los valores en distintas categorías
limits = [1, 2.5, 4]
category_lst = ['very_bad', 'bad', 'good', 'supreme']
categories_dct = {category: [] for category in category_lst}

for item in review_lst:
    if item <= limits[0]:
        categories_dct[category_lst[0]].append(item)
    elif item > limits[0] and item <= limits[1]:
        categories_dct[category_lst[1]].append(item)
    elif item > limits[1] and item <= limits[2]:
        categories_dct[category_lst[2]].append(item)
    else:
        categories_dct[category_lst[3]].append(item)

for lst, reviews in categories_dct.items():
    print(f"{lst}: {reviews}")

# Discretización de los valores en 5 rangos homogéneos
cut_categories = pd.cut(review_lst, 5, labels=['Category 1', 'Category 2', 'Category 3', 'Category 4', 'Category 5'])
print("\n{}".format(cut_categories.value_counts()))

qcut_categories = pd.cut(review_lst, 5, labels=['Category 1', 'Category 2', 'Category 3', 'Category 4', 'Category 5'])
print("\n{}".format(qcut_categories.value_counts()))

Reviews:
[0.1 0.5 2.9 4.  3.4 3.2 1.5 4.  3.8 2.4 3.6 2.6 2.  0.6 1.8 2.1 3.7 3.3
 1.5 3.5 3.6 2.6 2.4 4.3 4.3 3.8 1.7 2.  4.5 1.8 5.  0.3 4.2 2.  1.6 2.8
 0.  2.6 0.1 3.7 2.7 3.8 1.5 1.6 4.2 4.  1.4 0.6 4.5 4.7 3.9 3.4 1.4 4.5
 4.9 2.4 1.4 2.8 1.8 2.1 3.2 3.9 0.  4.3 1.7 2.2 4.1 0.  0.4 0.8 3.5 3.2
 2.4 0.7 0.3 0.6 1.6 2.2 3.3 1.9 2.  1.7 1.6 5.  2.1 0.3 1.1 1.8 0.4 3.5
 3.6 4.7 2.2 4.6 4.8 0.9 0.8 4.1 1.  1.3 3.5 0.6 3.1 0.5 2.6 0.5 0.1 2.2
 4.1 1.  1.6 4.1 0.3 3.3 0.7 3.7 0.7 5.  2.  4.5 3.5 4.9 1.3 3.4 0.3 3.7
 1.1 3.5 3.2 2.8 1.7 4.1 3.4 2.1 4.  3.9 4.7 1.4 5.  4.9 0.  4.2 4.3 1.4
 1.  2.8 2.5 0.9 1.4 2.2 2.8 0.5 2.9 5.  1.3 4.7 0.7 4.3 4.7 1.3 2.2 5.
 2.2 2.6 3.9 2.6 1.5 4.  4.2 2.8 0.4 1.9 2.8 0.3 1.9 4.9 0.4 3.3 4.6 2.4
 2.2 2.5 0.8 0.1 3.1 1.6 3.7 4.9 0.7 3.8 4.  3.6 1.3 2.2 4.7 3.7 1.4 3.5
 2.8 1.6]

very_bad: [0.1, 0.5, 0.6, 0.3, 0.0, 0.1, 0.6, 0.0, 0.0, 0.4, 0.8, 0.7, 0.3, 0.6, 0.3, 0.4, 0.9, 0.8, 1.0, 0.6, 0.5, 0.5, 0.1, 1.0, 0.3, 0.7, 0.7, 0.3, 0.0, 1.0, 0.9, 0.5, 0.7, 0.