# Examen Primera Convocatoria

In [1]:
# Your imports HERE !!!!
import numpy as np
import pandas as pd


C:\Users\pepel\AppData\Local\Temp\ipykernel_36064\4080809545.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## 01 - 1 pt
- Dado un array de elementos, escribir una función, que reciba dicho array como parámetro de entrada y devuelva el elemento repetido. Usando plain Python, sin ninguna librería.

In [2]:
# Your solution HERE !!!!
def repeated_element(lst):
    elements_viewed = []
    for number in lst:
        if number in elements_viewed:
            return number
        else:
            elements_viewed.append(number)

In [3]:
array_src = [4, 8, 0, 3, 6, 2, 1, 5, 3, 9, 7]
expected_rep_element = 3
rep_element = repeated_element(array_src) # This calls your function repeated_element
assert(expected_rep_element == rep_element)  # This will fail if the element is not found correctly

## 02 - 1pt
- Genera una matriz con valores aleatorios de 0 a 100 de dimensiones 16x16
- Calcula los siguentes estadísticos en la matriz anterior, por fila (el resultado de cada uno debe ser un array de dimensiones 1x16)
  - Suma de los elementos de cada fila
  - Media de los elementos de cada fila
  - Valores mínimos de cada fila
  - Valores máximos de cada fila

In [28]:
# Your solution HERE !!!!
matrix = np.random.randint(0, 101, size=(16, 16))
print(matrix)

print(f"\nSuma de las filas: {np.sum(matrix, axis=1).reshape(1, 16)}")
print(f"Media de las filas: {np.mean(matrix, axis=1).reshape(1, 16)}")
print(f"Mínimo de cada fila: {np.min(matrix, axis=1).reshape(1, 16)}")
print(f"Máximo de cada fila: {np.max(matrix, axis=1).reshape(1, 16)}")

[[ 93  22  85  18   6  94  87  50  48  67  53  45  70   9  13  94]
 [ 68  43  73  59  70 100  54  70  10  43  27  58  23  53  40  46]
 [  7  54  18  16  93  35  62  47  18  22  49  42  58  98  64  56]
 [ 44  69  71  59  18  31  58  63   3  54  66  31  75  25  27  61]
 [ 27  18   7  93  91  80  75  23  27  30  33  99   9  34  23  66]
 [ 80  92  11  48  24  90  14  49  72  17  20  21  59  52  98  88]
 [ 16  63  99  85  45  63  28  59   5  96  19  38  78  77  90  88]
 [ 36  78  22  13  61  36  33  90  56  69  65  49   2  28  93  40]
 [ 42  97  80   0  25   3  46  56   9  67  95  55  84  23   1  27]
 [ 31  85  60  49  11   3  66  87  87   6   0  52  20  98  80  48]
 [ 65  32  22  85  19  22  77  80  93  70   0  86   7  92 100   1]
 [ 22  56  89  89  88  38  75   1  88  60  59  93  14  72  31  44]
 [ 16  41   8  27  59  65  36  33  32  45  59  35   5   9  33  92]
 [  5  83  19  49  27  54   0  84  80  13  37  43  88  26  89  95]
 [ 96  50  75  20  67  59  73  73  74  10  96   6  94  67  83 

## 03 - 1pt

- Generar un dataframe de 3x4 dimensiones con valores númericos aleatorios [0,10]
- Darle un índice semántico alfanumérico
- Aplicarle una función lambda que obtenga la diferencia entre el máximo y mínimo de cada fila

In [14]:
# Your solution HERE !!!!
matrix = np.random.randint(0, 11, size=(3, 4))
print(matrix)

df = pd.DataFrame(matrix, index=['a', 'b', 'c'], columns=['col1', 'col2', 'col3', 'col4'])
print()
display(df)

output_df = df.apply(lambda row: row.max() - row.min(), axis=1)
print()
display(output_df)

[[ 8  0  6  4]
 [ 1  4  5  5]
 [ 1  0 10  9]]



col1  col2  col3  col4
a     8     0     6     4
b     1     4     5     5
c     1     0    10     9

a     8
b     4
c    10
dtype: int32

## 04 - 1pt
- Crear un array de NumPy de dimensiones 8x5, con números enteros aleatorios en el rango [-100, 100]
- Ejecutar en este orden

  1. Reemplazar los valores de todos aquellos números múltiplos de 5 por 100
  2. Reemplazar los valores de todos aquellos números múltiplos de 3 por Nan
  3. Averiguar cuantos elementos tienen Nan por fila
  4. Reemplazar los valores de Nan por 0

In [27]:
# Your solution HERE !!!!
arr = np.random.randint(-100, 101, size=(8, 5))
print(arr)

arr = np.where(arr%5==0, 100, arr)
print()
print(arr)

arr = np.where(arr%3==0, np.nan, arr)
print()
print(arr)

print("\n{}".format(np.isnan(arr).sum(axis=1)))

arr = np.where(np.isnan(arr), 0, arr)
print()
print(arr)

[[ -4  -4  44 -56  54]
 [  7  28  97 -37 -98]
 [ 69  80  96  23  43]
 [ 40 -83  -3 -22  81]
 [-87  53  -3 -44   6]
 [-88  85  95 -60  88]
 [-91 -80 -95  97 -90]
 [ 76  45 -32 -38 -77]]

[[ -4  -4  44 -56  54]
 [  7  28  97 -37 -98]
 [ 69 100  96  23  43]
 [100 -83  -3 -22  81]
 [-87  53  -3 -44   6]
 [-88 100 100 100  88]
 [-91 100 100  97 100]
 [ 76 100 -32 -38 -77]]

[[ -4.  -4.  44. -56.  nan]
 [  7.  28.  97. -37. -98.]
 [ nan 100.  nan  23.  43.]
 [100. -83.  nan -22.  nan]
 [ nan  53.  nan -44.  nan]
 [-88. 100. 100. 100.  88.]
 [-91. 100. 100.  97. 100.]
 [ 76. 100. -32. -38. -77.]]

[1 0 2 2 3 0 0 0]

[[ -4.  -4.  44. -56.   0.]
 [  7.  28.  97. -37. -98.]
 [  0. 100.   0.  23.  43.]
 [100. -83.   0. -22.   0.]
 [  0.  53.   0. -44.   0.]
 [-88. 100. 100. 100.  88.]
 [-91. 100. 100.  97. 100.]
 [ 76. 100. -32. -38. -77.]]


## 05 - 1pt
- Crear una función que reciba una lista de strings y devuelva una serie de pandas, y convierta el primer y último carácter de la palabra de cada elemento de la serie a mayúsculas

In [54]:
# Your solution HERE !!!!
def first_last_uppercase(lst):
    new_lst = []
    for item in lst:
        item = item[0].upper() + item[1:-1] + item[-1].upper()
        new_lst.append(item)

    return pd.Series(new_lst)

def first_last_uppercase2(lst):
    new_lst = [item[0].upper() + item[1:-1] + item[-1].upper() for item in lst]
    return pd.Series(new_lst)

def first_last_uppercase3(lst):
    input_series = pd.Series(lst)
    return input_series.apply(lambda item: item[0].upper() + item[1:-1] + item[-1].upper())

In [61]:
languages = ['python', 'php', 'java', 'javascript', 'c++', 'sql']
expected_output = pd.Series(['PythoN', 'PhP', 'JavA', 'JavascripT', 'C++', 'SqL'])
output = first_last_uppercase(languages)  # This calls your function first_last_uppercase
assert(expected_output.equals(output))  # This will fail if the two lists are different

0        PythoN
1           PhP
2          JavA
3    JavascripT
4           C++
5           SqL
dtype: object

## 06 - 3 pt
- Adjunto al notebook se puede encontrar un fichero 'ine_paro_exam.csv' que contiene datos del INE referentes al paro en España
- Las columnas son las siguientes:
  - Sexo, los datos de esa fila se refieren a hombres, mujeres o ambos sexos
  - Provincias, los datos de esa fila son totales para todo el pais, o de alguna provincia en particular
  - Tasas, que tipo de tasa representa el valor de la fila, es de actividad, paro o empleo
  - Periodo, a que periodo de tiempo aplica el dato, año y trimestre
  - Total, el dato de la tasa

Se pide lo siguiente:
  - Cargar los datos en un dataframe de Pandas y analizar los atributos
  - ¿Cuantos valores nulos hay por columna? Eliminar las filas que tienen nulo en la columna "Total"
  - Obtener la media anual de la tasa de paro, para ambos sexos y para el total nacional
  - Mostrar un resumen, donde en las filas aparezcan las provincias, y las tres tasas posibles (actividad, paro, empleo) en las columnas (obteniendo la media). Ordenar dicho resumen por la media de la tasa de paro ascendentemente
  - Representar graficamente una figura, sobre los datos para el total nacional, de las tres diferentes tasas, cada tasa en una subfigura, de manera que en cada subfigura se represente la evolución por trimestre de cada año (cada año se considera una linea con un color diferente)
  - ![logo](plot.png)

In [4]:
# Your solution HERE !!!!


## 07
- La serie de Fibonacci es una sucesión de números, en la cual cada número es la suma de los dos anteriores. Los dos primeros son siempre 0 y 1.
  - $F_0 = 0$
  - $F_1 = 1$
  - $F_n = F_{n-1} + F_{n-2}$
- Crear un generador infinito de números de Fibonacci.

In [8]:
# Your solution HERE !!!!
def fibonacci_generator():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a+b

In [10]:
fibo = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]
g = fibonacci_generator()  # This calls tour function fibonacci_generator
expected_output = [next(g) for n in range(len(fibo))]
assert(fibo == expected_output)  # This will fail if the output is not as expected

## 08 - 1pt
- Crear una lista de meses de Enero a Diciembre (eje X)
- Generar datos aleatorios para el eje Y, hacerlo 3 veces distintas (Y0, Y1 e Y2)
- Representar las 3 secuencias de datos aleatorios en una sola figura usando matplotlib
- Añadir una leyenda para poder identificar cada secuencia
- Nombrar las 3 secuencias de la siguiente manera ("Facebook", "Twitter", "Instagram")
- Añadir un título y nombres a los dos ejes
- Añadir una anotación (texto y flecha) a uno de los gráficos

In [32]:
# Your solution HERE !!!!
