<h1 style = "font-size:3rem;color:orange">Examen segunda convocatoria 2024</h1>

#### Librerías

In [2]:
import numpy as np

# 1 - 1.25 pt
Dado una lista de valores, cree un diccionario cuya clave sea el dato de la lista y el valor sea el resto de la división entre 6. No se deben incluir en el diccionario los valores cuyo resto es igual a cero.

In [14]:
def dct_items(lst):
    return {item: item % 6 for item in lst if item % 6 != 0}

In [15]:
ls_val = [30, 23, 7, 39, 55,  5, -4]
dc_res = dct_items(ls_val)  # This calls your function
dc_solucion = {23: 5, 7: 1, 39: 3, 55: 1, 5: 5, -4: 2}
assert(dc_res == dc_solucion), "Solución incorrecta"

# 2 - 1.25 pt
Realice con numpy:
- Una matriz 4x2 (A) y un vector 4x1 (b) con valores aleatorios
- Calcule la inversa de la multiplicación A traspuesta por la misma matriz, multiplíquelo por la matriz traspuesta de A y el vector b: $x =(A^{T}  A)^{-1} A^{T}b$ 
- Multiplique $x$ por un array de dos valores aleatorios.

In [13]:
A = np.random.randint(0, 10, size=(4, 2))
b = np.random.randint(0, 10, size=(4, 1))

print(A)
print(b)

x = np.dot(np.invert(np.dot(np.transpose(A), A)), np.dot(np.transpose(A), b))

print()
print(x)

[[5 9]
 [7 9]
 [1 4]
 [8 6]]
[[0]
 [7]
 [6]
 [4]]

[[-30051]
 [-37872]]


# 3 - 1.25 pt

Se pide crear un generador que recorra una lista dada y, que en cada llamada, devuelva la media de los valores contiguos y el valor central definido por la posición del índice de dicha lista. Es decir, dada la lista [12, 3, 9, 3, 6], el generador devolverá en la primera iteración la media de 12 y 3 dando como resultado 7.5. En la segunda iteración será 12, 3 y 9, resultando 8. El último valor que devolverá será 3 y 6, resultando 4.5.

In [27]:
def generador_medias(lst):
    position = 0
    while position < len(lst):
        if position == 0:
            yield np.round((lst[position] + lst[position + 1]) / 2, 1)
        elif position == len(lst) - 1:
            yield np.round((lst[position - 1] + lst[position]) / 2, 1)
        else:
            yield np.round((lst[position - 1] + lst[position] + lst[position + 1]) / 3, 1)
        position += 1

In [29]:
ls_num = [12, 3, 9, 3, 6]
gen = generador_medias(ls_num)
ls_res = []
ls_solucion = [7.5, 8.0, 5.0, 6.0, 4.5]
for i in gen:
    ls_res.append(i)
assert (ls_res==ls_solucion), "Solución incorrecta"

# 4 - 1.25 pt

Se pide crear una función que reciba un array de NumPy y devuelva otro en el cual estén marcados como True los elementos duplicados (a partir de la segunda ocurrencia), y como False los no repetidos o las primeras ocurrencias de los duplicados.

In [30]:
def find_duplicates(lst):
    output_lst = []
    dct = []
    for item in lst:
        if item not in dct:
            output_lst.append(False)
            dct.append(item)
        else:
            output_lst.append(True)
    
    return output_lst

In [31]:
numbers = np.array([4, 4, 4, 3, 8, 1, 9, 6, 1, 5, 9, 4, 0, 2])
expected_output = np.array([False, True, True, False, False, False, False, False, True, False, True, True, False, False])
output = find_duplicates(numbers)   # This calls your function find_duplicates
assert(np.array_equal(expected_output, output))  # This will fail if the result is not as expected