<h1 style = "font-size:3rem;color:orange">Examen segunda convocatoria 2024</h1>

#### Librerías

In [1]:
import numpy as np

# 1 - 1.25 pt
Dado una lista de valores, cree un diccionario cuya clave sea el dato de la lista y el valor sea el resto de la división entre 6. No se deben incluir en el diccionario los valores cuyo resto es igual a cero.

In [2]:
def dct_items(lst):
    return {item: item % 6 for item in lst if item % 6 != 0}

In [3]:
ls_val = [30, 23, 7, 39, 55,  5, -4]
dc_res = dct_items(ls_val)  # This calls your function
dc_solucion = {23: 5, 7: 1, 39: 3, 55: 1, 5: 5, -4: 2}
assert(dc_res == dc_solucion), "Solución incorrecta"

# 2 - 1.25 pt
Realice con numpy:
- Una matriz 4x2 (A) y un vector 4x1 (b) con valores aleatorios
- Calcule la inversa de la multiplicación A traspuesta por la misma matriz, multiplíquelo por la matriz traspuesta de A y el vector b: $x =(A^{T}  A)^{-1} A^{T}b$ 
- Multiplique $x$ por un array de dos valores aleatorios.

In [9]:
A = np.random.randint(0, 10, size=(4, 2))
b = np.random.randint(0, 10, size=(4, 1))

print(A)
print(b)

x = np.dot(np.invert(np.dot(np.transpose(A), A)), np.dot(np.transpose(A), b))

print(x)

[[6 5]
 [4 8]
 [8 9]
 [2 8]]
[[2]
 [4]
 [8]
 [3]]
[[-32696]
 [-47228]]
