# Examen Primera Convocatoria

In [165]:
# Your imports HERE !!!!
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import os

## 01 - 1.25pt
- Crear un array de NumPy de dimensiones 5x5, con números enteros aleatorios en el rango [-40, 40]
- Hacer los siguientes reemplazos en orden
    - Reemplazar todos los valores multiplos de 3 por 1
    - Reemplazar todos los valores pares positivos por 0
    - Reemplazar todos los valores pares negativos por Nan
- Averiguar cuantos elementos tienen Nan por fila

In [73]:
# Your solution HERE !!!!
array = np.random.randint(-40, 41, (5, 5))
array

array([[ -2,  39, -18,  20,  34],
       [  5,  27, -25, -16,  27],
       [  1,  -3,  -9,  -8,  19],
       [ 39, -32, -25, -11, -19],
       [ 35, -31,  22, -13, -37]])

In [74]:
array = np.where(array % 3 == 0, 1, array)
array

array([[ -2,   1,   1,  20,  34],
       [  5,   1, -25, -16,   1],
       [  1,   1,   1,  -8,  19],
       [  1, -32, -25, -11, -19],
       [ 35, -31,  22, -13, -37]])

In [75]:
array = np.where((array > 0) & (array % 2 == 0), 0, array)
array

array([[ -2,   1,   1,   0,   0],
       [  5,   1, -25, -16,   1],
       [  1,   1,   1,  -8,  19],
       [  1, -32, -25, -11, -19],
       [ 35, -31,   0, -13, -37]])

In [76]:
array = np.where((array < 0) & (array % 2 == 0), np.nan, array)
array

array([[ nan,   1.,   1.,   0.,   0.],
       [  5.,   1., -25.,  nan,   1.],
       [  1.,   1.,   1.,  nan,  19.],
       [  1.,  nan, -25., -11., -19.],
       [ 35., -31.,   0., -13., -37.]])

In [78]:
display(array)
new_array = pd.DataFrame(array)
new_array = new_array.transpose()
new_array.isna().sum()

array([[ nan,   1.,   1.,   0.,   0.],
       [  5.,   1., -25.,  nan,   1.],
       [  1.,   1.,   1.,  nan,  19.],
       [  1.,  nan, -25., -11., -19.],
       [ 35., -31.,   0., -13., -37.]])

0    1
1    1
2    1
3    1
4    0
dtype: int64

## 02 - 1.25pt
- Escribir un generador que genere todos los factores de un número. Un factor es un número natural que puede dividir exactamente a otro número.

In [ ]:
number = 1000
expected_factors = [1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 125, 200, 250, 500, 1000]
gen = factor_generator(number) # This calls tour function factor_generator
output = [next(gen) for n in range(len(expected_factors))]
assert(expected_factors == output)  # This will fail if the element is not found correctly

In [85]:
# Your solution HERE !!!!
number = 1000

def factor_generator(n):
    result = []
    for i in range(1, n+1):
        if n % i == 0:
            result.append(i)
    return result

print(factor_generator(number))

[1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 125, 200, 250, 500, 1000]


In [86]:
gen = factor_generator(number)
expected_factors = [1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 125, 200, 250, 500, 1000]
assert(expected_factors == gen)

## 03 - 1.25pt
- Escribir una función que reciba un Dataframe, en la columna "name" convierta el primer carácter de cada nombre a mayúsculas.

In [ ]:
dataframe = pd.DataFrame({
    'name': ['tamayo','tanjiro','inosuke', 'zenitsu', 'nezuko'],
    'date_of_birth ': ['13/01/2002','18/03/1999','21/11/1998','10/10/2002','05/04/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

expected_dataframe = pd.DataFrame({
    'name': ['Tamayo', 'Tanjiro', 'Inosuke', 'Zenitsu', 'Nezuko'],
    'date_of_birth ': ['13/01/2002','18/03/1999','21/11/1998','10/10/2002','05/04/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

output = capitalize_name(dataframe) # This calls your function capitalize_name
assert(expected_dataframe.equals(output)) # This will fail if result is not as expected

In [95]:
# Your solution HERE !!!!
dataframe = pd.DataFrame({
    'name': ['tamayo','tanjiro','inosuke', 'zenitsu', 'nezuko'],
    'date_of_birth ': ['13/01/2002','18/03/1999','21/11/1998','10/10/2002','05/04/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

display(dataframe)

def capitalize_name(df):
    df['name'] = df['name'].apply(lambda x: x[0].upper()+x[1:])
    return df

display(capitalize_name(dataframe))

name date_of_birth    age
0   tamayo     13/01/2002  18.5
1  tanjiro     18/03/1999  21.2
2  inosuke     21/11/1998  22.5
3  zenitsu     10/10/2002  22.0
4   nezuko     05/04/1997  23.0

name date_of_birth    age
0   Tamayo     13/01/2002  18.5
1  Tanjiro     18/03/1999  21.2
2  Inosuke     21/11/1998  22.5
3  Zenitsu     10/10/2002  22.0
4   Nezuko     05/04/1997  23.0

## 04 - 1.25pt
- 200 personas hacen una review de una película, dándole una puntuación de 0.0 a 5.0 a dicha película
- Crear una lista aleatoria con las posibles puntuaciones, es decir, 200 puntuaciones entre 0.0 y 5.0
- Discretizar dichas puntuaciones en 4 categorias [muy mala, mala, buena, excelente], los límites de cada categoría son a libre elección
- Discretizar dichas puntuaciones en 5 categorías distribuidas con rangos homogéneos (similar cantidad de valores en cada categoría)
- Mostrar las categorías creadas y cuantos elementos hay en cada una de ellas

In [161]:
# Your solution HERE !!!!
random_list = []

for i in range(200):
    random_list.append(np.random.random() * 5)

print(random_list)

[3.2348382550824177, 4.820555577108289, 3.635983495442998, 1.3661136976347983, 4.589364682324452, 1.0618676704958334, 0.1108236310769356, 3.56457657817685, 3.941423048918997, 0.25197795258364797, 2.6844193404093275, 4.302365141984739, 4.6827692723139025, 1.2255333669748065, 4.47505294633558, 1.8183355875612555, 3.547793699212672, 0.39806197982432623, 3.4653618850362653, 0.6291374468912603, 0.4445272581243809, 0.47479169792486564, 4.511273489103338, 1.115999785049362, 0.23862464563293995, 4.899769289054485, 2.639076858679946, 1.4978935994978604, 0.501244531001962, 0.055345286061395105, 4.70711421694988, 4.969844957196791, 0.11188681056596594, 0.28416102332439963, 2.909039280742668, 2.233419892924347, 2.651955567607448, 3.8173639502432377, 1.7712857629528589, 2.1175855343386547, 0.32240440986364305, 2.7613476223552977, 2.8070766600802717, 2.5149903571659045, 2.804110778522241, 4.496600855869003, 3.732195045155007, 0.5507709704677322, 0.41199040301064027, 3.4812519149790115, 3.39605298964

In [162]:
very_bad, bad, good, excellent = [], [], [], []

for item in random_list:
    if item <= 1.5:
        very_bad.append(item)
    elif item > 1.5 and item <= 2.5:
        bad.append(item)
    elif item > 2.5 and item <= 4:
        good.append(item)
    else:
        excellent.append(item)

In [163]:
cat_1, cat_2, cat_3, cat_4, cat_5 = [], [], [], [], []

for item in random_list:
    if item <= 1:
        cat_1.append(item)
    elif item > 1 and item <= 2:
        cat_2.append(item)
    elif item > 2 and item <= 3:
        cat_3.append(item)
    elif item > 3 and item <= 4:
        cat_4.append(item)
    else:
        cat_5.append(item)

In [164]:
# Discretización 1
print(very_bad)
print("Elementos: ", len(very_bad))
print(bad)
print("Elementos: ", len(bad))
print(good)
print("Elementos: ", len(good))
print(excellent)
print("Elementos: ", len(excellent))

# Discretización 2
print('\n' + 'Discretización 2' + '\n')
print(cat_1)
print("Elementos: ", len(cat_1))
print(cat_2)
print("Elementos: ", len(cat_2))
print(cat_3)
print("Elementos: ", len(cat_3))
print(cat_4)
print("Elementos: ", len(cat_4))
print(cat_5)
print("Elementos: ", len(cat_5))

[1.3661136976347983, 1.0618676704958334, 0.1108236310769356, 0.25197795258364797, 1.2255333669748065, 0.39806197982432623, 0.6291374468912603, 0.4445272581243809, 0.47479169792486564, 1.115999785049362, 0.23862464563293995, 1.4978935994978604, 0.501244531001962, 0.055345286061395105, 0.11188681056596594, 0.28416102332439963, 0.32240440986364305, 0.5507709704677322, 0.41199040301064027, 0.5031367567781647, 0.11862522911861129, 1.0103291644857753, 0.07908531444736855, 1.0745356615567248, 1.3500528371087228, 0.710689206498818, 1.114164222894637, 0.29678006484518016, 1.1592805059917692, 0.42221728149583027, 0.07071542634118966, 0.6912286719165439, 0.10881108029333508, 0.37086873397397024, 1.2951769986556916, 0.5331495732583164, 1.4729971899950156, 1.4103854434819114, 0.7132234214156291, 0.15143332806207832, 1.027374914584177, 1.1153063288200222, 0.8976358742927176, 1.2472014058846281, 0.6942791899190148, 0.32951455170322774, 0.8234169239973199, 0.17556544426190535, 0.7711397880363391, 1.28

## 05 - 5pt

Se dispone de dos conjuntos de datos, ambos datasets se adjuntan en la pregunta del examen
- [01MIAR_aircraft.csv](https://www.kaggle.com/datasets/dianaddx/aircraft-wildlife-strikes-1990-2023/): incidentes de avión.
- [01MIAR_airports.csv](https://ourairports.com/data/): aeropuertos de todo el mundo, con el nombre y país de cada aeropuerto.

1. Carga el fichero 01MIAR_aircraft.csv en un dataframe de Pandas y:
    - Muestra las seis primeras filas.
    - Calcula el porcentaje de valores nulos por columna.
    - Muestra en una figura, con un tamaño de 8 de ancho y 4 de alto, una gráfica de tipo puntos (scatter), la localización de los incidentes en base a la longitud y latitud.
    > Pista, descarta del df original los registros cuyos valores de latitud y longitud no se encuentren en el rango de coordenadas esféricas, siendo la longitud valida en el rango [-180, 180], y la latitud valida en el rango [-90, 90].
    - Muestra en una figura un conteo de incidentes sobre la columna 'AIRCRAFT' por año, en el gráfico debe aparecer una columna por cada 'DAMAGE_LEVEL' distinto en el dataframe. La gráfica debe ser de tipo linea con diferentes subplots.
    > Pista, agrupa primero y aplique una gráfica de relación.
    
2. Carga el fichero 01MIAR_airports.csv en un dataframe de Pandas y:
    - Muestra el número de filas y columnas
    - Cambia los valores a minúsculas de columna de nombre de aeropuerto en este dataframe y en el del apartado anterior.
    - Con el propósito de disponer del país de los aeropuertos, junta ambos dataframes para obtener un nuevo dataframe con todos los registros de incidentes de avión y los países de los aeropuertos. Como clave, utilizar el nombre del aeropuerto modificado en el anterior apartado.
    - Como resultado se debe disponer un dataframe con 254222 registros.
    - Muestra el número de registros que no disponen de dato en el atributo "iso_country".
    - Elimina todos los registros que que tengan nulos alguna de las columnas 'DAMAGE_LEVEL' y 'iso_country'.
    - Sobre el resultado anterior, crea una tabla contando el número de incidentes por país, en las filas deben aparecer todos los paises posibles y en las columnas debe de estar el tipo de 'DAMAGE_LEVEL'.

In [168]:
# Your solution HERE !!!!

# Apartado 1.
aircraft_rute = os.path.join('01MIAR_aircraft.csv')
aircraft = pd.read_csv(aircraft_rute)

display(aircraft.head(6))

INCIDENT_DATE                      AIRPORT  LATITUDE  LONGITUDE   AIRCRAFT  \
0     6/22/1996              SACRAMENTO INTL  38.69542 -121.59077  B-737-300   
1     6/26/1996          DENVER INTL AIRPORT  39.85841 -104.66700  B-737-300   
2      7/1/1996              EPPLEY AIRFIELD  41.30252  -95.89417  B-757-200   
3      7/1/1996  WASHINGTON DULLES INTL ARPT  38.94453  -77.45581      A-320   
4      7/1/1996              LA GUARDIA ARPT  40.77724  -73.87261      A-320   
5      5/6/1991             SAN ANTONIO INTL  29.53369  -98.46978  B-727-100   

  DAMAGE_LEVEL  
0          NaN  
1          NaN  
2            N  
3            N  
4            M  
5            N

In [172]:
a = aircraft.loc[pd.isnull(aircraft['DAMAGE_LEVEL'])].sum()

INCIDENT_DATE    6/22/19966/26/19969/19/19909/14/19905/10/19907...
AIRPORT          SACRAMENTO INTLDENVER INTL AIRPORTDALLAS/FORT ...
LATITUDE                                            3707058.015728
LONGITUDE                                          -9228473.449471
AIRCRAFT         B-737-300B-737-300MD-80UNKNOWNDC-10L-1011UNKNO...
DAMAGE_LEVEL                                                     0
dtype: object


In [169]:
# Apartado 2
airports_rute = os.path.join('01MIAR_airports.csv')
airports = pd.read_csv(airports_rute)

display(airports)

id    ident           type                       name  \
0        6523      00A       heliport          Total RF Heliport   
1      323361     00AA  small_airport       Aero B Ranch Airport   
2        6524     00AK  small_airport               Lowell Field   
3        6525     00AL  small_airport               Epps Airpark   
4      506791     00AN  small_airport       Katmai Lodge Airport   
...       ...      ...            ...                        ...   
77453   46378  ZZ-0001       heliport            Sealand Helipad   
77454  307326  ZZ-0002  small_airport  Glorioso Islands Airstrip   
77455  346788  ZZ-0003  small_airport      Fainting Goat Airport   
77456  342102     ZZZW         closed     Scandium City Heliport   
77457  313629     ZZZZ  small_airport     Satsuma Iōjima Airport   

       latitude_deg  longitude_deg  elevation_ft continent iso_country  \
0         40.070985     -74.933689          11.0       NaN          US   
1         38.704022    -101.473911        3435.0       NaN          US   
2         59.947733    -151.692524         450.0       NaN          US   
3         34.864799     -86.770302         820.0       NaN          US   
4         59.093287    -156.456699          80.0       NaN          US   
...             ...            ...           ...       ...         ...   
77453     51.894444       1.482500          40.0        EU          GB   
77454    -11.584278      47.296389          11.0        AF          TF   
77455     32.110587     -97.356312         690.0       NaN          US   
77456     69.355287    -138.939310           4.0       NaN          CA   
77457     30.784722     130.270556         338.0        AS          JP   

      iso_region         municipality scheduled_service gps_code iata_code  \
0          US-PA             Bensalem                no     K00A       NaN   
1          US-KS                Leoti                no     00AA       NaN   
2          US-AK         Anchor Point                no     00AK       NaN   
3          US-AL              Harvest                no     00AL       NaN   
4          US-AK          King Salmon                no     00AN       NaN   
...          ...                  ...               ...      ...       ...   
77453     GB-ENG              Sealand                no      NaN       NaN   
77454     TF-U-A     Grande Glorieuse                no      NaN       NaN   
77455      US-TX                 Blum                no     87TX       NaN   
77456      CA-YT  (Old) Scandium City                no      NaN       NaN   
77457      JP-46              Mishima                no     RJX7       NaN   

      local_code                                          home_link  \
0            00A  https://www.penndot.pa.gov/TravelInPA/airports...   
1           00AA                                                NaN   
2           00AK                                                NaN   
3           00AL                                                NaN   
4           00AN                                                NaN   
...          ...                                                ...   
77453        NaN                         http://www.sealandgov.org/   
77454        NaN                                                NaN   
77455       87TX                                                NaN   
77456        NaN                                                NaN   
77457       RJX7                                                NaN   

                                          wikipedia_link  \
0                                                    NaN   
1                                                    NaN   
2                                                    NaN   
3                                                    NaN   
4                                                    NaN   
...                                                  ...   
77453  https://en.wikipedia.org/wiki/Principality_of_...   
77454                              